### ISSUE TITLE
Chrome Extension 

### ISSUE THREAD

**Issue by beshoo** [shekohex/wadump#2]
Hi, thanks for the great app.
Is it possible some how ti make chrome extension to do thst?

**Comment by shekohex** [comment]
this code can be easily compiled to `WASM` (Web Assembly) and run in the browser too.
but I hadn't made any Chrome Extension before, also I guess for security extensions can't access these packets? maybe I'm wrong here I need to research more, but overall it is a great idea to have .. but I guess we will go for a simple CLI for now.

**Comment by beshoo** [comment]
100%
