### ISSUE TITLE
Install problem 

### ISSUE THREAD

**Issue by beshoo** [shekohex/wadump#4]
First off all i am nope in rust.

I have this error 
```

error: expected one of `!` or `::`, found `#`  
 --> bin/wadump/src/main.rs:7:1
  |
6 | Packets
  |        - expected one of `!` or `::`
7 | #[derive(Debug, FromArgs)]
  | ^ unexpected token

error: aborting due to previous error          

error: could not compile `wadump`.
```

**Comment by beshoo** [comment]
https://github.com/shekohex/wadump/blob/d1cbaa5a7f88c59a78c7771752f6fe1abeea42ae/bin/wadump/src/main.rs#L16


Why it is not working for me? It stop at this line

**Comment by shekohex** [comment]
could you rebase to master branch and try again? since I guess you made changes to the `main.rs` file that made your code can't be compiled.

**Comment by beshoo** [comment]
New error after rebase
```

   Compiling wa v0.1.0 (/home/mymujeeb/whatsapp_debug/wadump/wa)                   Compiling wadump v0.1.0 (/home/mymujeeb/whatsapp_debug/wadump/bin/wadump)    error: linking with `cc` failed: exit code: 1                                     |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/local/lib/rustlib/x86_64-unknown-
. 
. 
. 
. 
. 
cc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-ldl" "-lutil"
  = note: /usr/bin/ld: cannot find -ldbus-1
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error                                           
error: could not compile `wadump`. 
```

**Comment by shekohex** [comment]
try install `libdbus-1` I guess it is missing in your system.

**Comment by beshoo** [comment]
Works! :) let me start testing :)

**Comment by beshoo** [comment]
New Error when feeding Encrypt key

```
[MAX]root:[/home/mymujeeb/whatsapp_debug/wadump/target/debug]./wadump --outgoing -m M0VCMDg5QzZEMUVFNEZGOTVFOEMsEIBzlcEvHrDlknQC8o62Nqby4d4dDvGyIPn1nqZshYK/2gvpVPtsqG5tT6CfmJyjoDgJzVDGCXWR5Zi6WDjstzwjOqLu8Ff6c3LsK533M6SwqQm6ImidF1O9HwvImm5AR2ryKA7bp0Y+bsmGQPrvYo2b4TKTRADc2DvFTSI46FoSWxkmpd9qtyLIzduq63LlQV4=
Enter Encryption Key (base64):
Error: SecretServiceError(Dbus(D-Bus error: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11 (org.freedesktop.DBus.Error.NotSupported)))
[MAX]root:[/home/mymujeeb/whatsapp_debug/wadump/target/debug]

```

**Comment by beshoo** [comment]
I am using Linux Centos 7 box!

**Comment by shekohex** [comment]
it seems that there is an issue in your D-Bus, the problem that we need to store your keys in a secure keychain, I will make a patch to read the Keys from env so it would be easy to test too.

**Comment by beshoo** [comment]
Hmmm . i hope if I can run the test asap!
I installed the 
 **dbus-launch** 
will it help?

**Comment by beshoo** [comment]
```
dbus-launch --exit-with-session ./wadump
Enter Encryption Key (base64):
Error: SecretServiceError(Dbus(D-Bus error: The name org.freedesktop.secrets was not provided by any .service files (org.freedesktop.DBus.Error.ServiceUnknown)))

```

Same problem! i think i need to wait your patch

**Comment by shekohex** [comment]
should be fixed in #5

**Comment by beshoo** [comment]
Thanks 
I add the export for both of parm.
Now :
[MAX]root:[/home/mymujeeb/whatsapp_debug/wadump/target/debug]./wadump --outgoing -m M0VCMEMxQ0FFNjlFMTUwQjk3MkIsEIBmPmUM4F2zefa28pHjZZyrZfVCWbAxXWImvquvSY3WoFRNyJVvxHpy7eaJWY6fpc57SRommAsRzVgu92ae+EU/r/GKdldDdncIoPt0iDMUh7cnqvrGN3rIkJk8V6XIwoGjxTdlNztdsg7UDS01V4gz/C9vZZt2ISEopodmTZpRsF/7qQPycgDlgo/n5nXMut0iJz55J/xuBpYv4Lou4nNVtBM5IV2TUQLn6HOld47Bkw==
**Error: InvalidByte(43, 61)**
Which I copy and paste from the crome WS section

**Comment by shekohex** [comment]
could you make sure that the keys are valid base64 and stored correctly?

`echo $WADUMP_ENC_KEY` and `echo $WADUMP_MAC_KEY` also try with a message is received by your side first

**Comment by beshoo** [comment]
WORKS 100%

**Comment by beshoo** [comment]
It will be GREAT to make it as addon to the chrome, a new column to WS windows! WAW :)

**Comment by Ased2235** [comment]
> could you make sure that the keys are valid base64 and stored correctly?
> 
> `echo $WADUMP_ENC_KEY` and `echo $WADUMP_MAC_KEY` also try with a message is received by your side first

i'm having same issue but when i echo those 2, it return empty
