### ISSUE TITLE
Picture node

### ISSUE THREAD

**Issue by viniciuscenci** [shekohex/wadump#6]
When I try to decrypt a binary message, I got this error:

"got unhandled node of desc: picture"

The message that I'm trying to decrypt is form the profile picture upload function...

Thanks! Great tool!

**Comment by shekohex** [comment]
I guess WhatsApp updated their protocol buffer code, so this tool needs to be updated too.

Sadly, I dont have enough internet right now to update the web app again and get the protobuf.

but anyway, the code that prints this error is here https://github.com/shekohex/wadump/blob/2ec33e6bceb99ccbcc80f60c42434aed6a60dea8/bin/wadump/src/main.rs#L129 

the other thing you should look into, is when you get the `picture` node desc, is how to decode the buffer back into its own struct.

Could you also share what it prints after this error message? it should dump the full node for debugging.

**Comment by viniciuscenci** [comment]
Ok, thank you!

The full output:

```
Message Tag: 1632481859.--33
got unhandled node of desc: picture
Node {
    desc: "picture",
    attributes: {
        "id": 1632481859.--33,
        "type": set,
        "jid": xxx@c.us,
    },
    content: [
        Node {
            desc: "image",
            attributes: {},
            content: [...],
        },
        Node {
            desc: "preview",
            attributes: {},
            content: [...],
        },
    ],
}
```

**Comment by shekohex** [comment]
Okay, as it says the content is a list and the first item is the image and the second is a preview.

Now we just need to know how we should decode it back, you have to try doing it in the code.

**Comment by shekohex** [comment]
Closed as fixed
